### ISSUE TITLE
More examples?

### ISSUE THREAD

**Issue by mathiasbynens** [tc39/proposal-regexp-unicode-property-escapes#11]
Other, possibly more useful examples than those mentioned in https://github.com/mathiasbynens/es-regexp-unicode-property-escapes#illustrative-examples are welcome!

@patch, I’d imagine you have a few of those up your sleeve.

**Comment by vsemozhetbyt** [comment]
Not sure if this can be used as an example, but FWIW)

I use this script to check mixing Latin letters with non-Latin ones. No extra care of edge cases, only simple mixes.

https://gist.github.com/vsemozhetbyt/0efd0e3d6abc511e95968f9f38120156

Examples of a mixed text, a command line and an output:

https://gist.github.com/vsemozhetbyt/0efd0e3d6abc511e95968f9f38120156#gistcomment-2143306
