### ISSUE TITLE
Normative Reference concerns

### ISSUE THREAD

**Issue by allenwb** [tc39/proposal-regexp-unicode-property-escapes#13]
Unicode Consortium documents that are essential to the interpretation of this specification should be normatively referenced. If they are not already listed in ECMA-262 [clause 3](https://tc39.github.io/ecma262/#sec-normative-references) they need to be added (also see https://github.com/tc39/ecma262/issues/726). Those additions should be listed as part of the proposed spec. text.

The documents that appear to be in need of normative references are: UTS #18 and UAX #44

A consistent style for referencing Unicode Consortium documents should be used throughout ECMA-262. Existing references in ECMA-262 typically spell out the full document title, such as: Unicode Standard Annex #31, Identifier and Pattern Syntax. This proposal uses abbreviated references such as: UTS18.

**Comment by mathiasbynens** [comment]
UTR#51 should be mentioned too.
