### ISSUE TITLE
UnicodeMatchX: Static Semantics vs. Runtime Sematntics

### ISSUE THREAD

**Issue by allenwb** [tc39/proposal-regexp-unicode-property-escapes#16]
UnicodeMatchProperty and UnicodeMatchPropertyValue seem like they should be labels as "Static Semantics" rather than "Runtime Semantics".

In general, static semantic abstract operations are those whose only inputs are directly derived from parsed source code (in this case, a parsed RegExp pattern) and hence don't have any dependencies upon runtime state.  They are things that a compiler or linter might be able to determine, without actually running the program being processed.

**Comment by mathiasbynens** [comment]
Good catch! I forgot to change this when we decided to throw early errors instead of run-time errors. (b4dccc4404dcf4ac74e39243c85b2ec416008dfb, #5)
