### ISSUE TITLE
Provide shortcut for word characters, numbers, and spaces

### ISSUE THREAD

**Issue by DemiMarie** [tc39/proposal-regexp-unicode-property-escapes#19]
Since `\w`, `\s`, and `\d` are still not Unicode-aware even with the `u` flag, programmers will still be forced to have a build step or write long, ugly regexps for this purpose.  There should be a shortcut for these.

**Comment by mathiasbynens** [comment]
The proposal for that got shut down two years ago: https://github.com/mathiasbynens/es-regexp-unicode-character-class-escapes/blob/master/d-w-b.md
