### ISSUE TITLE
Provide a shorthand for unicode-aware \w

### ISSUE THREAD

**Issue by DemiMarie** [tc39/proposal-regexp-unicode-property-escapes#22]
The Unicode-aware replacement for `\w` is very verbose and undiscoverable.  There should be a shortcut syntax.

**Comment by mathiasbynens** [comment]
There was a pre-ES6 [proposal to change the meaning of `\w`, `\d`, and `\b` in Unicode mode](https://github.com/mathiasbynens/es-regexp-unicode-character-class-escapes/blob/master/d-w-b.md). It was ultimately rejected out of fear it would hurt adoption of the `u` flag.

We could reserve a shortcut of the form `\p{Word}` but that would cause a conflict if a property with that name is ever added to the Unicode Standard — something we cannot predict. We could make it `\p{_Word}` to make future collisions less likely but that’s kind of ugly.

It seems to me that the best we can do now is expose the primitives to let developers build equivalent regular expressions, which this proposal does.

**Comment by littledan** [comment]
Maybe the right place to make this proposal would be at the Unicode level, to add such a property, cc @srl295 .

**Comment by mathiasbynens** [comment]
Closing this issue as it’s not going to happen as part of this proposal.
