### ISSUE TITLE
Early errors or runtime errors for invalid property escapes?

### ISSUE THREAD

**Issue by mathiasbynens** [tc39/proposal-regexp-unicode-property-escapes#5]
Per the current proposal (b4025a08c5d2f116d81b98528d179f24011068cb) `/\p{invalid}/u` or `/\p{Block=invalidvalue}/u` throws a `SyntaxError` at runtime.

Should these be early errors instead?
#### Early errors — pros
- Consistency with things like [`\u{110000}`](https://tc39.github.io/ecma262/#sec-string-literals-static-semantics-early-errors) which are early errors.
#### Early errors — cons
- Possible performance cost (?)
  - E.g. in the case of `/\p{invalid}/u`, the engine would have to check if `invalid` is a general category value _or_ a binary property and trigger an early error if not. Doing this at runtime (as in the current proposal) _sounds_ more performant to me but I may be wrong here. @hashseed, any thoughts?

I don’t have a strong opinion on this.

**Comment by mathiasbynens** [comment]
@hashseed

**Comment by hashseed** [comment]
Currently V8 is not really the paragon for early errors. Following code does not cause a syntax error:

``` js
function f() {
  /\u{110000}/u
}
```

nor does

``` js
function f() {
  /\u{invalid}/u
}
```

Validating regexp literals down to unicode property classes could have performance impact though. Then again, V8's current experimental implementation is not optimized at all, and I doubt that it would matter that much in practice. You can still use the RegExp constructor if you want lazy validation.

**Comment by mathiasbynens** [comment]
@littledan seems to prefer early errors as per https://github.com/mathiasbynens/es-regexp-unicode-property-escapes/issues/6#issuecomment-236374946. Care to elaborate why?

**Comment by littledan** [comment]
RegExps generally have early errors for malformed things. The general idea seems to be that compilation might as well be pretty static. V8 doesn’t do this—it parses RegExps only when reaching them. We don’t have any errors for malformed RegExps that come when they are reached, however. An implementation like V8’s RegExp engine expands out the Unicode character classes into a series of ranges, as if in a gigantic `[]`, from the parser. That seems to me like a reasonable mental model to guide us towards an early error here—there’s only one error time, and the spec has that time early. Anyway, just my opinion, not really strongly held.

**Comment by patch** [comment]
Here’s what was introduced in Perl 5.24, released 2016-05-09:

### [Regular expression compilation errors](https://metacpan.org/pod/release/RJBS/perl-5.24.0/pod/perldelta.pod#Regular-expression-compilation-errors)

> Some regular expression patterns that had runtime errors now don't compile at all.
> 
> Almost all Unicode properties using the `\p{}` and `\P{}` regular expression pattern constructs are now checked for validity at pattern compilation time, and invalid ones will cause the program to not compile. In earlier releases, this check was often deferred until run time. Whenever an error check is moved from run- to compile time, erroneous code is caught 100% of the time, whereas before it would only get caught if and when the offending portion actually gets executed, which for unreachable code might be never.

Along with the new error message `Can't find Unicode property definition "%s" in regex` described in [perldiag](https://metacpan.org/pod/release/RJBS/perl-5.24.0/pod/perldiag.pod#Cant-find-Unicode-property-definition-s).

**Comment by mathiasbynens** [comment]
Thanks for the input, everyone. The proposal now triggers early errors instead of runtime errors for invalid property escapes.
