### ISSUE TITLE
Missing grammatical productions?

### ISSUE THREAD

**Issue by mathiasbynens** [tc39/proposal-regexp-unicode-property-escapes#6]
```
09:37:04 <littledan> Well there was also concern that some grammatical productions were missing
```

@littledan, @bterlson, or anyone else who was present at the meeting, could you elaborate?

**Comment by mathiasbynens** [comment]
It’s probably the grammar for `UnicodePropertyName` and `UnicodePropertyValue`/`LoneUnicodePropertyNameOrValue`.
- `UnicodePropertyName`: `[A-Za-z_]`
- `UnicodePropertyValue`/`LoneUnicodePropertyNameOrValue`: `[0-9A-Za-z_]`

**Comment by littledan** [comment]
We should also have early errors, not runtime errors, if the values are missing or incorrect.

**Comment by littledan** [comment]
Never mind, you filed https://github.com/mathiasbynens/es-regexp-unicode-property-escapes/issues/5 for this.
