### ISSUE TITLE
Which properties are included?

### ISSUE THREAD

**Issue by littledan** [tc39/proposal-regexp-unicode-property-escapes#9]
The current spec draft is fairly vague on which Unicode properties are included. I suggest following [UTS 18](http://unicode.org/reports/tr18/#RL1.2) here, though their `\p` syntax is general to the point of being a little ridiculous. Mark Davis suggested,

> In general, we'd recommend at least http://unicode.org/reports/tr18/#RL1.2. But see also http://unicode.org/reports/tr18/#Full_Properties. Ideally you'd do all of those, but I can understand taking "baby steps".
> 
> Of the latter, probably the most useful are the Name, and the properties the feed into http://unicode.org/reports/tr18/#Compatibility_Properties, perhaps also the break properties.
> 
> It partly depends on what is being implemented in JavaScript. For example, a complicated text editor (like Google Docs) can use many more properties.

**Comment by mathiasbynens** [comment]
> The current spec draft is fairly vague on which Unicode properties are included.

Could you please clarify how https://github.com/mathiasbynens/es-regexp-unicode-property-escapes/blob/87926ec6fef4dfc797e1359bd15c2f4b5f525ee6/spec.html#L127 is vague?

> I suggest following [UTS 18](http://unicode.org/reports/tr18/#RL1.2) […]

See above — it already mentions UTS 18.

> Of the latter, probably the most useful are […] Name […]

`\p{Name=…}` is not supported for now. Since `\u{…}` is already available I don’t think there is a strong need for it. (Why use `\p{Name=TETRAGRAM FOR CENTRE}` when you could use `\u{1D306}`?) I should add that to the FAQ.

**Comment by littledan** [comment]
Sorry! I was just being a lazy spec reviewer and somehow missed that.

I think `\p{Name=TETRAGRAM FOR CENTRE}` is nice because it gives a more semantically meaningful thing than the number--it removes something that you have to look up. But I'm also OK if we leave it out the first time around.

**Comment by mathiasbynens** [comment]
What did you think about the “Implementations may extend Unicode property support to the remaining enumeration or binary properties” part? Perhaps that _is_ too vague. Should we allow implementations to differ in their property support at the cost of interoperability, or not?

**Comment by littledan** [comment]
I don't think we should allow that. I think we should explicitly state all of the ones that are included, and permit no more, to avoid compatibility risks.

**Comment by mathiasbynens** [comment]
Done.
